### PR TITLE
Rearrange modules

### PR DESCRIPTION
**Pull request by ghoshbishakh**
@archie94 take a look and merge

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
@archie94 continue working after merging

**Comment by archie94** [comment]
@ghoshbishakh any reason why the UpdatePeerListViewThread is not run? It removes the inactive peers from the peer list.

**Comment by ghoshbishakh** [comment]
I am going step by step. I will add that.

**Comment by archie94** [comment]
okay I am pushing whatever I have done

**Comment by ghoshbishakh** [comment]
Sure

**Pull request merged**
