### PR TITLE
Minor: change logs

### PR DESCRIPTION
**Pull request by ghoshbishakh**

### CODE REVIEW

**Comment by ghoshbishakh** [comment]
more changes coming. dont merge now

**Comment by archie94** [comment]
Merge now ?

**Comment by ghoshbishakh** [comment]
you did something that resulted in merge conflicts
ill have to resolve them first

**Comment by archie94** [comment]
Yeah I added the method to download missing files. But you have done that already.  :+1:

**Comment by ghoshbishakh** [comment]
@archie94 my fault I should have reminded you to merge before working

**Comment by ghoshbishakh** [comment]
Anyway ill fix the merge conflicts but donot change anything more

**Comment by ghoshbishakh** [comment]
@archie94 check and merge

**Pull request merged**
